// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDHS3P90cDDJ_qI3Mo3hriyIz3_sQECGzA',
//     appId: '1:104994313627:web:525937750fdb485473bd3e',
//     messagingSenderId: '104994313627',
//     projectId: 'foodhub-94375',
//     authDomain: 'foodhub-94375.firebaseapp.com',
//     storageBucket: 'foodhub-94375.appspot.com',
//     measurementId: 'G-HYRBCE66ED',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBOiP8VE7GDwOPKV6_cQ8oym2P96zf9ZEQ',
//     appId: '1:104994313627:android:2b70d3bd54aa91ba73bd3e',
//     messagingSenderId: '104994313627',
//     projectId: 'foodhub-94375',
//     storageBucket: 'foodhub-94375.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAnja3Pv0hS1gRwxqIowg9px9uGpGitZaI',
//     appId: '1:104994313627:ios:dbe79473b8865d3373bd3e',
//     messagingSenderId: '104994313627',
//     projectId: 'foodhub-94375',
//     storageBucket: 'foodhub-94375.appspot.com',
//     iosBundleId: 'com.example.foodhub',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAnja3Pv0hS1gRwxqIowg9px9uGpGitZaI',
//     appId: '1:104994313627:ios:a32a664515371d3f73bd3e',
//     messagingSenderId: '104994313627',
//     projectId: 'foodhub-94375',
//     storageBucket: 'foodhub-94375.appspot.com',
//     iosBundleId: 'com.example.foodhub.RunnerTests',
//   );
// }
